require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lessons", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Lesson. As you add validations to Lesson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Lesson.create! valid_attributes
      get lessons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lesson = Lesson.create! valid_attributes
      get lesson_url(lesson)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lesson_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      lesson = Lesson.create! valid_attributes
      get edit_lesson_url(lesson)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lesson" do
        expect {
          post lessons_url, params: { lesson: valid_attributes }
        }.to change(Lesson, :count).by(1)
      end

      it "redirects to the created lesson" do
        post lessons_url, params: { lesson: valid_attributes }
        expect(response).to redirect_to(lesson_url(Lesson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lesson" do
        expect {
          post lessons_url, params: { lesson: invalid_attributes }
        }.to change(Lesson, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post lessons_url, params: { lesson: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lesson" do
        lesson = Lesson.create! valid_attributes
        patch lesson_url(lesson), params: { lesson: new_attributes }
        lesson.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lesson" do
        lesson = Lesson.create! valid_attributes
        patch lesson_url(lesson), params: { lesson: new_attributes }
        lesson.reload
        expect(response).to redirect_to(lesson_url(lesson))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        lesson = Lesson.create! valid_attributes
        patch lesson_url(lesson), params: { lesson: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lesson" do
      lesson = Lesson.create! valid_attributes
      expect {
        delete lesson_url(lesson)
      }.to change(Lesson, :count).by(-1)
    end

    it "redirects to the lessons list" do
      lesson = Lesson.create! valid_attributes
      delete lesson_url(lesson)
      expect(response).to redirect_to(lessons_url)
    end
  end
end
